name: heroku-deploy
on:
  push:
    branches: [master]
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_app_name: "desolate-anchorage-03663"
        heroku_email: "irranggaa@gmail.com"