name: learn-github-actions
on: [push]
jobs:
  test-go-get:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - run: go get github.com/gin-gonic/gin
      - run: go get github.com/joho/godotenv